# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Always Be Learning ðŸ‘¨ðŸ»â€ðŸ’»
paginate:       42
baseurl:        "/ABL"
url:            "https://www.trilliwon.com/ABL/"


# Google Analytics

google_analytics: UA-93898714-2

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
kramdown:
  auto_ids:       true
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  input:          GFM
  hard_wrap:      false
  footnote_nr:    1
  show_warnings:  false

highlighter: rouge

# About
author:
  name:         trilliwon
  url:          http://www.trilliwon.com
  email:        trilliwon@gmail.com
  description: > # this means to ignore newlines until "baseurl:"
    I will write my stories here.

twitter_username: trilliwon
github_username:  trilliwon


# Custom vars
version:        1.0.0
github:
  repo:         https://github.com/trilliwon/ABL

# Gems
gems:
  - jekyll-paginate
  - jekyll-sitemap